// data/index.ts
import {
  FinancialData,
  CategoryData,
  MenuItem,
  Customer,
  Order,
  Notification,
  GalleryItem,
  Testimonial,
  FAQ,
  ProfileData,
} from "./types";

export const initialFinancialData: FinancialData[] = [
  {
    id: "TRX001",
    date: "2023-08-15",
    description: "Penjualan Makanan",
    category: "Food Sales",
    amount: 450000,
    type: "income",
    paymentMethod: "GoPay",
    status: "completed",
  },
  {
    id: "TRX002",
    date: "2023-08-15",
    description: "Penjualan Minuman",
    category: "Beverage Sales",
    amount: 120000,
    type: "income",
    paymentMethod: "OVO",
    status: "completed",
  },
  {
    id: "TRX003",
    date: "2023-08-14",
    description: "Pembelian Bahan Baku",
    category: "Ingredients",
    amount: 350000,
    type: "expense",
    paymentMethod: "Transfer",
    status: "completed",
  },
  {
    id: "TRX004",
    date: "2023-08-14",
    description: "Biaya Listrik",
    category: "Utilities",
    amount: 85000,
    type: "expense",
    paymentMethod: "Transfer",
    status: "completed",
  },
  {
    id: "TRX005",
    date: "2023-08-13",
    description: "Penjualan Catering",
    category: "Catering",
    amount: 1200000,
    type: "income",
    paymentMethod: "BCA",
    status: "completed",
  },
  {
    id: "TRX006",
    date: "2023-08-13",
    description: "Gaji Karyawan",
    category: "Salary",
    amount: 2500000,
    type: "expense",
    paymentMethod: "Transfer",
    status: "completed",
  },
  {
    id: "TRX007",
    date: "2023-08-12",
    description: "Penjualan Makanan",
    category: "Food Sales",
    amount: 380000,
    type: "income",
    paymentMethod: "Cash",
    status: "completed",
  },
  {
    id: "TRX008",
    date: "2023-08-12",
    description: "Biaya Sewa",
    category: "Rent",
    amount: 1500000,
    type: "expense",
    paymentMethod: "Transfer",
    status: "completed",
  },
  {
    id: "TRX009",
    date: "2023-08-11",
    description: "Penjualan Minuman",
    category: "Beverage Sales",
    amount: 95000,
    type: "income",
    paymentMethod: "DANA",
    status: "pending",
  },
  {
    id: "TRX010",
    date: "2023-08-11",
    description: "Biaya Marketing",
    category: "Marketing",
    amount: 300000,
    type: "expense",
    paymentMethod: "Transfer",
    status: "completed",
  },
];

export const categories: CategoryData[] = [
  { name: "Food Sales", value: 45, color: "#FF6384" },
  { name: "Beverage Sales", value: 20, color: "#36A2EB" },
  { name: "Catering", value: 15, color: "#FFCE56" },
  { name: "Ingredients", value: 10, color: "#4BC0C0" },
  { name: "Utilities", value: 5, color: "#9966FF" },
  { name: "Salary", value: 10, color: "#FF9F40" },
  { name: "Rent", value: 20, color: "#C9CBCF" },
  { name: "Marketing", value: 5, color: "#7CFC00" },
];

export const paymentMethods = [
  { name: "GoPay", value: 35, color: "#00AED9" },
  { name: "OVO", value: 25, color: "#EB0029" },
  { name: "DANA", value: 15, color: "#0080FF" },
  { name: "BCA", value: 15, color: "#0066B2" },
  { name: "Cash", value: 10, color: "#4CAF50" },
];

export const initialMenuItems: MenuItem[] = [
  {
    id: 1,
    name: "Nasi Rames Komplit",
    description: "Nasi dengan lauk pilihan: ayam goreng, tempe, tahu, sayur, dan sambal",
    price: 25000,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    category: "Makanan Utama",
    isFavorite: true,
    isAvailable: true,
  },
  {
    id: 2,
    name: "Soto Ayam Kampung",
    description: "Soto ayam segar dengan suwir ayam kampung dan kentang",
    price: 20000,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    category: "Makanan Utama",
    isFavorite: true,
    isAvailable: true,
  },
  {
    id: 3,
    name: "Gado-Gado Jakarta",
    description: "Sayuran segar dengan bumbu kacang dan telur rebus",
    price: 18000,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    category: "Makanan Utama",
    isFavorite: true,
    isAvailable: true,
  },
  {
    id: 4,
    name: "Rendang Sapi Padang",
    description: "Daging sapi empuk dengan bumbu rendang autentik",
    price: 35000,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    category: "Makanan Utama",
    isFavorite: true,
    isAvailable: true,
  },
  {
    id: 5,
    name: "Ayam Goreng Lengkuas",
    description: "Ayam goreng dengan rempah lengkuas yang harum",
    price: 28000,
    image: "https://images.unsplash.com/photo-1623682247451-0ca2cddc009b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    category: "Makanan Utama",
    isFavorite: true,
    isAvailable: true,
  },
  {
    id: 6,
    name: "Es Teh Manis",
    description: "Teh manis dingin dengan es batu",
    price: 5000,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    category: "Minuman",
    isFavorite: true,
    isAvailable: true,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 1,
    name: "Budi Santoso",
    email: "budi@example.com",
    phone: "081234567890",
    address: "Jl. Sudirman No. 45, Jakarta Selatan",
    totalOrders: 12,
    joinDate: "2023-01-15",
  },
  {
    id: 2,
    name: "Siti Nurhaliza",
    email: "siti@example.com",
    phone: "081234567891",
    address: "Jl. Thamrin No. 12, Jakarta Pusat",
    totalOrders: 8,
    joinDate: "2023-02-20",
  },
  {
    id: 3,
    name: "Ahmad Fauzi",
    email: "ahmad@example.com",
    phone: "081234567892",
    address: "Jl. Gatot Subroto No. 30, Jakarta Selatan",
    totalOrders: 15,
    joinDate: "2023-01-10",
  },
  {
    id: 4,
    name: "Dewi Lestari",
    email: "dewi@example.com",
    phone: "081234567893",
    address: "Jl. Rasuna Said No. 5, Jakarta Selatan",
    totalOrders: 6,
    joinDate: "2023-03-05",
  },
  {
    id: 5,
    name: "Rudi Hermawan",
    email: "rudi@example.com",
    phone: "081234567894",
    address: "Jl. MH Thamrin No. 20, Jakarta Pusat",
    totalOrders: 10,
    joinDate: "2023-02-15",
  },
];

export const initialOrders: Order[] = [
  {
    id: "INV-2023081501",
    customer: "Budi Santoso",
    date: "2023-08-15",
    time: "12:30",
    items: [
      { name: "Nasi Rames Komplit", quantity: 2, price: 25000 },
      { name: "Es Teh Manis", quantity: 2, price: 5000 },
    ],
    amount: 60000,
    payment: "GoPay",
    status: "Selesai",
    deliveryOption: "Diantar",
    address: "Jl. Sudirman No. 45, Jakarta Selatan",
  },
  {
    id: "INV-2023081502",
    customer: "Siti Nurhaliza",
    date: "2023-08-15",
    time: "13:45",
    items: [
      { name: "Soto Ayam Kampung", quantity: 1, price: 20000 },
      { name: "Gado-Gado Jakarta", quantity: 1, price: 18000 },
    ],
    amount: 38000,
    payment: "BCA",
    status: "Diproses",
    deliveryOption: "Makan di Tempat",
    address: "-",
  },
  {
    id: "INV-2023081503",
    customer: "Ahmad Fauzi",
    date: "2023-08-14",
    time: "19:20",
    items: [
      { name: "Rendang Sapi Padang", quantity: 1, price: 35000 },
      { name: "Ayam Goreng Lengkuas", quantity: 1, price: 28000 },
      { name: "Es Teh Manis", quantity: 1, price: 5000 },
    ],
    amount: 68000,
    payment: "OVO",
    status: "Selesai",
    deliveryOption: "Diantar",
    address: "Jl. Gatot Subroto No. 30, Jakarta Selatan",
  },
];

export const initialNotifications: Notification[] = [
  {
    id: 1,
    title: "Pesanan Baru",
    message: "Budi Santoso telah melakukan pemesanan",
    time: "5 menit yang lalu",
    isRead: false,
    type: "order",
  },
  {
    id: 2,
    title: "Pembayaran Diterima",
    message: "Pembayaran untuk INV-2023081502 telah diterima",
    time: "1 jam yang lalu",
    isRead: false,
    type: "payment",
  },
  {
    id: 3,
    title: "Stok Menipis",
    message: "Stok untuk Ayam Goreng Lengkuas hampir habis",
    time: "3 jam yang lalu",
    isRead: true,
    type: "stock",
  },
  {
    id: 4,
    title: "Ulasan Baru",
    message: "Siti Nurhaliza memberikan ulasan 5 bintang",
    time: "1 hari yang lalu",
    isRead: true,
    type: "review",
  },
];

export const initialGalleryItems: GalleryItem[] = [
  {
    id: 1,
    src: "https://images.unsplash.com/photo-1601050691389-d98d48d8c1ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    alt: "Makanan Nasi Rames",
    caption: "Nasi Rames Komplit dengan lauk pilihan",
    category: "Makanan",
  },
  {
    id: 2,
    src: "https://picsum.photos/600/400?random=2",
    alt: "Interior Warteg",
    caption: "Ruangan makan yang nyaman dan bersih",
    category: "Interior",
  },
  {
    id: 3,
    src: "https://picsum.photos/600/400?random=3",
    alt: "Soto Ayam",
    caption: "Soto Ayam Kampung segar",
    category: "Makanan",
  },
  {
    id: 4,
    src: "https://picsum.photos/600/400?random=4",
    alt: "Minuman",
    caption: "Berbagai pilihan minuman segar",
    category: "Minuman",
  },
  {
    id: 5,
    src: "https://picsum.photos/600/400?random=5",
    alt: "Karyawan",
    caption: "Tim kami yang ramah dan profesional",
    category: "Tim",
  },
  {
    id: 6,
    src: "https://picsum.photos/600/400?random=6",
    alt: "Gado-Gado",
    caption: "Gado-Gado Jakarta dengan bumbu kacang autentik",
    category: "Makanan",
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: 1,
    name: "Budi Santoso",
    avatar: "https://picsum.photos/100/100?random=1",
    comment: "Sekarang makan di warteg jadi lebih praktis! Tidak perlu antri lagi.",
    rating: 5,
    date: "2023-08-10",
    status: "published",
  },
  {
    id: 2,
    name: "Siti Nurhaliza",
    avatar: "https://picsum.photos/100/100?random=2",
    comment: "Menu digitalnya sangat membantu, bisa lihat gambar makanan sebelum pesan.",
    rating: 4,
    date: "2023-08-08",
    status: "published",
  },
  {
    id: 3,
    name: "Ahmad Fauzi",
    avatar: "https://picsum.photos/100/100?random=3",
    comment: "Pembayaran dengan QRIS sangat memudahkan, tidak perlu bawa uang tunai.",
    rating: 5,
    date: "2023-08-05",
    status: "published",
  },
];

export const initialFAQs: FAQ[] = [
  {
    id: 1,
    question: "Bagaimana cara memesan makanan di Warteg Sederhana?",
    answer: "Anda dapat memesan makanan melalui aplikasi digital kami. Pilih menu yang diinginkan, tambahkan ke keranjang, lalu lanjutkan ke pembayaran.",
    category: "Pemesanan",
    order: 1,
    status: "published",
  },
  {
    id: 2,
    question: "Apakah makanan dapat diantar ke rumah?",
    answer: "Ya, kami menyediakan layanan pengantaran dengan biaya tambahan sesuai jarak. Estimasi waktu pengantaran 30-45 menit.",
    category: "Pengantaran",
    order: 2,
    status: "published",
  },
  {
    id: 3,
    question: "Metode pembayaran apa saja yang tersedia?",
    answer: "Kami menerima pembayaran melalui transfer bank (BCA, Mandiri, BNI) dan e-wallet (GoPay, OVO, DANA).",
    category: "Pembayaran",
    order: 3,
    status: "published",
  },
  {
    id: 4,
    question: "Apakah ada minimal pemesanan?",
    answer: "Ya, minimal pemesanan untuk layanan pengantaran adalah Rp15.000. Untuk makan di tempat tidak ada minimal.",
    category: "Pemesanan",
    order: 4,
    status: "published",
  },
  {
    id: 5,
    question: "Bagaimana jika ada keluhan dengan pesanan?",
    answer: "Silakan hubungi kami melalui nomor telepon atau email yang tertera. Kami akan segera menindaklanjuti keluhan Anda.",
    category: "Layanan Pelanggan",
    order: 5,
    status: "published",
  },
];

export const initialProfileData: ProfileData = {
  name: "Warteg Sederhana",
  description: "Menyajikan masakan rumahan autentik dengan bahan segar pilihan",
  address: "Jl. Merdeka No. 123, Jakarta Pusat",
  operatingHours: "08:00 - 22:00 WIB",
  phone: "(021) 1234-5678",
  email: "info@wartegsederhana.com",
  minOrder: 15000,
  deliveryFee: 5000,
  deliveryTime: "30-45 menit",
  logo: "/images/product/eat2.jpeg",
  coverImage: "/images/product/eat2.jpeg",
  socialMedia: {
    facebook: "https://facebook.com/wartegsederhana",
    instagram: "https://instagram.com/wartegsederhana",
  },
};